FROM kasmweb/kali-rolling-desktop:1.19.0-rolling-weekly

LABEL org.opencontainers.image.source="https://github.com/perspective0labs/kasmregistry_mdoublesee" \
      org.opencontainers.image.description="Perspective Labs Kasm workspace wrapper for kali-linux"
