FROM kasmweb/blender:1.19.0-rolling-daily
LABEL org.opencontainers.image.source="https://github.com/perspective0labs/kasmregistry_mdoublesee"
LABEL org.opencontainers.image.description="Perspective Labs Kasm Blender workspace wrapper"
