FROM kasmweb/chrome:1.19.0-rolling-weekly
LABEL org.opencontainers.image.source="https://github.com/perspective0labs/kasmregistry_mdoublesee"
LABEL org.opencontainers.image.description="Perspective Labs Kasm litellm workspace wrapper"
